version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - tianhaoz95
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - tianhaoz95
