pull_request_rules:
  - name: auto merge for dependabot
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      merge:
        method: squash
  - name: auto merge for README sync
    conditions:
      - author~=^tianhaoz95$
      - title~=^\[README sync\]
    actions:
      merge:
        method: squash