---
Style/MultipleComparison:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiteralPrefix:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Lint/UselessAssignment:
  Exclude:
  - "**/spec/**/*"
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/DotPosition:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Layout/HeredocIndentation:
  Enabled: false
Style/MixinGrouping:
  Exclude:
  - "**/spec/**/*"
Lint/SuppressedException:
  Enabled: false
Lint/UnusedBlockArgument:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/WordArray:
  MinSize: 19
Style/SignalException:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals
Metrics/ClassLength:
  Max: 320
Layout/LineLength:
  Max: 370
Metrics/ParameterLists:
  Max: 17
Metrics/PerceivedComplexity:
  Max: 18
Style/GuardClause:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Lint/ParenthesesAsGroupedExpression:
  Exclude:
  - "**/spec/**/*"
Naming/PredicateName:
  Enabled: false
Style/PerlBackrefs:
  Enabled: false
Layout/SpaceAroundOperators:
  Exclude:
  - "**/spec/actions_specs/xcodebuild_spec.rb"
AllCops:
  TargetRubyVersion: 2.7
  Include:
  - "*/lib/assets/*Template"
  - "*/lib/assets/*TemplateAndroid"
  Exclude:
  - "**/lib/assets/custom_action_template.rb"
  - "./vendor/**/*"
  - "**/lib/assets/DefaultFastfileTemplate"
  - "**/lib/assets/MatchfileTemplate"
  - "**/spec/fixtures/broken_files/broken_file.rb"
Naming/FileName:
  Exclude:
  - "**/Dangerfile"
  - "**/Brewfile"
  - "**/Gemfile"
  - "**/Podfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/Deliverfile"
  - "**/Snapfile"
  - "**/*.gemspec"
Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/IfInsideElse:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
  - require
  - require_relative
  - fastlane_require
  - gem
  - program
  - command
  - raise
  - attr_accessor
  - attr_reader
  - desc
  - lane
  - private_lane
  - platform
  - to
  - describe
  - it
  - be
  - context
  - before
  - after
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
