name: Auto Approve
on: pull_request_target
jobs:
  auto-approve:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@v3.0.0
        if: |
          github.actor == 'dependabot[bot]' || 
            contains(github.event.pull_request.labels.*.name, 'safe to approve')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
