name: Pull Request Checks
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
jobs:
  spec-test:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
        contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
      - name: setup ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
          bundler-cache: true
      - name: run unit tests
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rake
      - name: run e2e tests
        run: |
          bundle exec fastlane test
          bundle exec fastlane test_no_version_code
  regression-test:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
        contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.6"
      - run: flutter create regression_test_app
      - name: Run regression test
        working-directory: ./regression_test_app/android
        run: |
          cp -r ../../regression/fastlane .
          cp ../../regression/Gemfile .
          bundle install
          bundle exec fastlane regression
  auto-approve:
    runs-on: ubuntu-latest
    needs: [spec-test, regression-test]
    steps:
      - uses: hmarr/auto-approve-action@v2.1.0
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
      - uses: hmarr/auto-approve-action@v2.1.0
        if: github.actor == 'allcontributors[bot]'
        with:
          github-token: "${{ secrets.USE_GITHUB_TOKEN }}"
