name: Publish Package to rubygems.org and GitHub Registry
on:
  push:
    branches:
      - "master"
    paths:
      - "lib/fastlane/plugin/flutter_version/version.rb"
jobs:
  release-to-ruby-gems:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2.3.4
      - name: setup ruby environment
        uses: actions/setup-ruby@v1.1.3
        with:
          ruby-version: "2.6"
      - name: setup release credentials
        env:
          RELEASE_TOKEN: ${{ secrets.RUBY_GEMS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          rm -rf ~/.gem/credentials
          mkdir -p ~/.gem
          echo "---" > ~/.gem/credentials
          echo ":github: Bearer ${GITHUB_TOKEN}" >> ~/.gem/credentials
          echo ":rubygems_api_key: ${RELEASE_TOKEN}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
      - name: release package
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
        run: |
          git config --global user.email "tianhaoz@umich.edu"
          git config --global user.name "Tianhao Zhou"
          echo "machine github.com login tianhaoz95 password $GITHUB_TOKEN" > ~/.netrc
          bundle install
          rake install
          gem push pkg/*.gem
          gem push --key github --host https://rubygems.pkg.github.com/tianhaoz95 pkg/*.gem
