name: Regression Test
on: push
jobs:
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - name: Initialize Flutter project
        run: flutter create regression_test_app
      - name: Run regression test
        working-directory: ./regression_test_app/android
        run: |
          cp -r ../../regression/fastlane .
          cp ../../regression/Gemfile .
          bundle install
          bundle exec fastlane regression
      
