name: Regression Test
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
jobs:
  regression-test:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
      contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.0.6'
      - name: Initialize Flutter project
        run: flutter create regression_test_app
      - name: Run regression test
        working-directory: ./regression_test_app/android
        run: |
          cp -r ../../regression/fastlane .
          cp ../../regression/Gemfile .
          bundle install
          bundle exec fastlane regression
      
