name: "Rubocop"
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
jobs:
  rubocop:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
      contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install dependencies
        run: bundle install
      - name: Rubocop run
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "
      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rubocop.sarif
