name: Run Tests
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  spec-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup ruby environment
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
          bundler-cache: true
      - name: run unit tests
        run: bundle exec rake
      - name: run e2e tests
        run: |
          bundle exec fastlane test
          bundle exec fastlane test_no_version_code
  regression-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2.10.0
        with:
          flutter-version: "2.0.6"
      - run: flutter create regression_test_app
      - name: Run regression test
        working-directory: ./regression_test_app/android
        run: |
          cp -r ../../regression/fastlane .
          cp ../../regression/Gemfile .
          bundle install
          bundle exec fastlane regression
