name: Sentry
on: push
jobs:
  spec-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install dependencies
        run: bundle install
      - name: sanity checks
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rake
      - name: run tests
        run: |
          bundle exec fastlane test
          bundle exec fastlane test_no_version_code
