name: sentry
on:
  push:
    branches: 
      - "master"
      - "dev/*"
      - "fix/*"
      - "refactor/*"
      - "chore/*"
  pull_request:
    branches:
      - "master"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - name: install dependencies
        run: bundle install
      - name: run tests
        run: bundle exec fastlane test
