name: Sentry
on:
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
jobs:
  spec-test:
    runs-on: ubuntu-latest
    if: |
      github.actor == 'dependabot[bot]' || 
      contains(github.event.pull_request.labels.*.name, 'safe to test')
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: install dependencies
        run: bundle install
      - name: sanity checks
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: bundle exec rake
      - name: run tests
        run: |
          bundle exec fastlane test
          bundle exec fastlane test_no_version_code
