name: sentry
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 'master'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: install dependencies
        run: bundle install
      - name: sanity checks
        run: bundle exec rake
      - name: run tests
        run: bundle exec fastlane test
